---
- hosts: all
  gather_facts: yes
  sudo: no
  vars_files:
    - private_vars.yml

  vars:
  - ansible_python_interpreter: /usr/bin/python

  tasks:
  - include: common/tasks/system.yml tags=system
  - include: common/tasks/git.yml tags=version_control
  - include: common/tasks/python_deps.yml tags=python
  - include: common/tasks/pythonz.yml tags=python
  - include: common/tasks/pycharm.yml tags=python
  - include: common/tasks/debian_desktop.yml tags=debian
  - include: common/tasks/postgresql.yml tags=pgsql
  - include: common/tasks/mysql.yml tags=mysql
