---
# Configuration of postgresql server

- name: Installing PostgreSQL server
  sudo: yes
  apt: pkg=postgresql,python-psycopg2,pgadmin3,libpq-dev state=installed

- name: Configuring postgres user
  sudo: yes
  ignore_errors: yes
  postgresql_user: user=postgres password=$psqlpassword state=present
  sudo_user: postgres


