- name: Checking Pythonz installation
  register: inst_pythonz
  file: path=/home/{{ username }}/.pythonz state=directory

- name: Installing Pythonz
  shell: curl -kL https://raw.github.com/saghul/pythonz/master/pythonz-install | bash
  when: inst_pythonz.changed

- name: Pythonz support in bashrc
  lineinfile: dest=/home/{{ username }}/.bashrc
              line="[[ -s $HOME/.pythonz/etc/bashrc ]] && source $HOME/.pythonz/etc/bashrc"
              regexp=".*?pythonz.*?"
              backup=yes
              state=present
              create=yes
  register: pythonz_bashrc

- name: Activating Pythonz support in bashrc
  shell: . /home/{{ username }}/.bashrc


- name: Checking CPython 3.6.0
  register: cpython360_installed
  shell: "[ -f /home/{{ username }}/.pythonz/pythons/CPython-3.6.0/bin/python ] && echo 'Found' || echo ''"

- name: Installing CPython 3.6.0
  when: (cpython360_installed.stdout != 'Found')
  shell: pythonz install 3.6.0rc1
