- name: Checking Pythonz installation
  register: inst_pythonz
  file: path=/home/${username}/.pythonz state=directory

- name: Installing Pythonz
  shell: curl -kL https://raw.github.com/saghul/pythonz/master/pythonz-install | bash
  when: inst_pythonz.changed

- name: Pythonz support in bashrc
  lineinfile: dest=/home/${username}/.bashrc
              line="[[ -s $HOME/.pythonz/etc/bashrc ]] && source $HOME/.pythonz/etc/bashrc"
              regexp=".*?pythonz.*?"
              backup=yes
              state=present
              create=yes
  register: pythonz_bashrc

- name: Activating Pythonz support in bashrc
  shell: source /home/${username}/.bashrc
  when: pythonz_bashrc.changed

- name: Checking CPython 2.6.8
  register: cpython268_installed
  shell: "[ -f /home/${username}/.pythonz/pythons/CPython-2.6.8/bin/python ] && echo 'Found' || echo ''"

- name: Installing CPython 2.6.8
  when: (not cpython268_installed.stdout)
  shell: pythonz install 2.6.8

- name: Checking CPython 3.3.2
  register: cpython332_installed
  shell: "[ -f /home/${username}/.pythonz/pythons/CPython-3.3.2/bin/python ] && echo 'Found' || echo ''"

- name: Installing CPython 3.3.2
  when: (not cpython332_installed.stdout)
  shell: pythonz install 3.3.2

